ERROR:django.request:Internal Server Error: /eigen/eigenvectorsCourse
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\国创\LinearAlgebraMachine-main\mysite\eigen\views.py", line 11, in eigenvectorsCourse
    mat = json.loads(request.body)['matrix']
  File "D:\Python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:django.request:Internal Server Error: /eigen/eigenvectorsCourse
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\国创\LinearAlgebraMachine-main\mysite\eigen\views.py", line 11, in eigenvectorsCourse
    mat = json.loads(request.body)['matrix']
  File "D:\Python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:django.request:Internal Server Error: /eigen/eigenvectorsCourse
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\国创\LinearAlgebraMachine-main\mysite\eigen\views.py", line 11, in eigenvectorsCourse
    mat = json.loads(request.body)['matrix']
  File "D:\Python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:django.request:Internal Server Error: /eigen/eigenvectorsCourse
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\国创\LinearAlgebraMachine-main\mysite\eigen\views.py", line 11, in eigenvectorsCourse
    mat = json.loads(request.body)['matrix']
  File "D:\Python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
