ERROR:django.request:Internal Server Error: /eigen/eigenCourse
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\anaconda\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\¹ú´´\LinearAlgebraMachine-main\mysite\eigen\views.py", line 13, in eigenCourse
    mat = json.loads(request.body)['matrix']
  File "D:\anaconda\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\anaconda\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\anaconda\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
